# Generated by Django 3.2 on 2021-04-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('good_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество товара')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('W', 'Wait'), ('M', 'Order is made'), ('R', 'Rejected')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodect_order_product', to='orders.order')),
            ],
        ),
    ]
