# Generated by Django 3.2 on 2021-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
