# Generated by Django 3.2 on 2021-04-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total_price',
        ),
    ]
