# Generated by Django 3.2 on 2021-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='good_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='good_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество товара'),
        ),
    ]
