# Generated by Django 3.2 on 2021-04-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New courier appointed'), ('T', 'The manager looked at the order and appointed a courier'), ('O', 'On my way'), ('D', 'Delivered'), ('С', 'Сanceled')], max_length=100),
        ),
    ]
